// <auto-generated />
namespace CoronaSupportPlatform.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class DBImprovementTenderEntityInheritance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBImprovementTenderEntityInheritance));
        
        string IMigrationMetadata.Id
        {
            get { return "202003221625223_DB-Improvement-TenderEntityInheritance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
