// <auto-generated />
namespace CoronaSupportPlatform.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class DBImprovementTenderAddresses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBImprovementTenderAddresses));
        
        string IMigrationMetadata.Id
        {
            get { return "202003242041026_DB-Improvement-TenderAddresses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
