// <auto-generated />
namespace CoronaSupportPlatform.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class DBImprovementTenderItemEntityInheritance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBImprovementTenderItemEntityInheritance));
        
        string IMigrationMetadata.Id
        {
            get { return "202003221639111_DB-Improvement-TenderItemEntityInheritance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
